Repository kaandesu/vue-paho-mqtt, pull requests merged in 2023-04, with the labels that each got.

#7 refactor: Unsubscribe All
  src/pahoMqttPlugin/index.ts
Labels: enhancement

#10 chore(typings): declared types for `globalProperties`, configured `eslint` and `prettier`
  .eslintrc.json
  .prettierrc
  package-lock.json
  package.json
  src/App.vue
  src/index.d.ts
  src/main.ts
  src/pahoMqttPlugin/index.ts
  src/pahoMqttPlugin/types.ts
  tsconfig.json
Labels: enhancement

#15 feature(changesets): added `changesets` and workflows, testing first version bump!
  .changeset/README.md
  .changeset/config.json
  .changeset/six-balloons-cheer.md
  .github/workflows/publish.yml
  .prettierrc
  package-lock.json
  package.json
  tsconfig.json
Labels: enhancement

#17 fix(changesets): fixed workflow duplication bug
  .github/workflows/publish.yml
Labels: bug

#26 feat: demo build config & npm script
  .gitignore
  package.json
  src/pahoMqttPlugin/types.ts
  vite.config.ts
Labels: enhancement

#31 fix: deploy workflow
  .github/workflows/deploy.yml
Labels: enhancement

#36 chore: update readme
  README.md
  src/pahoMqttPlugin/utils/mqttSettings.ts
  src/pahoMqttPlugin/utils/refs.ts
  tsconfig.json
Labels: documentation, enhancement

#42 feat: $mqtt global instance
  .changeset/slimy-dragons-burn.md
  README.md
  src/pahoMqttPlugin/index.ts
Labels: enhancement

#44 feat: added security policy, added scripts to contributing, adjusted package dependencies
  .changeset/fuzzy-games-hide.md
  CONTRIBUTING.md
  README.md
  SECURITY.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#46 chore: included broker tests to the build & fix createClient
  .changeset/green-eagles-walk.md
  CONTRIBUTING.md
  package.json
  src/main.ts
  src/pahoMqttPlugin/config/client.ts
  src/pahoMqttPlugin/config/constants.ts
  src/pahoMqttPlugin/utils/__tests__/utils.test.ts
  src/pahoMqttPlugin/utils/connectClient.ts
  src/setupTests.ts
Labels: documentation, enhancement

#50 chore(types): better type definitions
  README.md
  src/App.vue
  src/pahoMqttPlugin/config/__tests__/client.test.ts
  src/pahoMqttPlugin/config/__tests__/options.test.ts
  src/pahoMqttPlugin/config/client.ts
  src/pahoMqttPlugin/config/constants.ts
  src/pahoMqttPlugin/config/options.ts
  src/pahoMqttPlugin/functions/onConnect.ts
  src/pahoMqttPlugin/functions/onConnectionLost.ts
  src/pahoMqttPlugin/functions/onFailure.ts
  src/pahoMqttPlugin/functions/onMessageArrived.ts
  src/pahoMqttPlugin/index.ts
  src/pahoMqttPlugin/types.ts
  src/pahoMqttPlugin/types/types.ts
  src/pahoMqttPlugin/utils/SweetAlert.ts
  src/pahoMqttPlugin/utils/__tests__/utils.test.ts
  src/pahoMqttPlugin/utils/connectClient.ts
  src/pahoMqttPlugin/utils/disconnectClient.ts
  src/pahoMqttPlugin/utils/index.ts
  src/pahoMqttPlugin/utils/mqttSettings.ts
  src/pahoMqttPlugin/utils/msgHandlers.ts
  src/pahoMqttPlugin/utils/publish.ts
  src/pahoMqttPlugin/utils/refs.ts
  src/pahoMqttPlugin/utils/subscribe.ts
  src/pahoMqttPlugin/utils/unsubscribe.ts
  src/pahoMqttPlugin/utils/unsubscribeAll.ts
  tsconfig-build.json
  tsconfig.json
  vite.config.ts
Labels: enhancement
